### ISSUE TITLE
Swipe to show all apps feels indirect, could be quicker

### ISSUE THREAD

**Issue by jancborchardt** [postapczuk/Light-Android-Launcher#11]
Swipe is "indirect", meaning it does not directly swipe the view, it just triggers an animation. Would be much nicer and faster if it’s direct.

What we seem to need for that is using a [swipe view / ViewPager](https://developer.android.com/training/implementing-navigation/lateral#horizontal-paging):
![](https://cdn.journaldev.com/wp-content/uploads/2015/12/android-viewpager-output.gif)

Of course we would still have the minimal design with black background and light text and no other elements like header or tabs. :) What do you think @postapczuk?

**Comment by jancborchardt** [comment]
This might also fix the problem that swiping back often triggers accidental long-press? Cause then it’s just handled by Android.

**Comment by snug** [comment]
Big agree on this one, it would be great if it scrolls *as* you swipe, not after.

Two other things too,
 - All parts of the screen should be responsive to swiping.
 - Perhaps a slight "fade out" transition when swiping.

**Comment by jancborchardt** [comment]
> All parts of the screen should be responsive to swiping.

This part was already fixed via #7, just needs a release. :)

**Comment by postapczuk** [comment]
release is done already (available on github), but It's not available - it's triggered to build on fdroid.

**Comment by postapczuk** [comment]
@snug fixes are on fdroid

**Comment by jancborchardt** [comment]
Ok, let’s get back to the original topic of the indirect swiping then. :) → See the top post

**Comment by postapczuk** [comment]
working on it

**Comment by postapczuk** [comment]
done
