### ISSUE TITLE
Allow more than 5 apps on home screen

### ISSUE THREAD

**Issue by postapczuk** [postapczuk/Light-Android-Launcher#19]
Gray button "+ add more" at the end of the list that allows to add new applications

![lal](https://user-images.githubusercontent.com/19855347/49326922-88c05280-f559-11e8-9c2f-13c305c899d3.png)

**Comment by postapczuk** [comment]
working on it.

**Comment by jancborchardt** [comment]
Hehe, nice! I was also thinking about that!

Maybe we should call it "+ Add favorite" so it's clear it's not installation?

**Comment by jancborchardt** [comment]
Am also thinking that for less visual noise, it should be "+ Add favorite" initially, but once you used the button for the first time, we can change it to just "+".

What do you think?

**Comment by postapczuk** [comment]
yep. When i will finish the task - I will give you the code to review.

**Comment by snug** [comment]
@postapczuk In this same vein, are you able to make it so we can also select less than five apps? I generally only use Phone, Signal and Maps and would like only those apps visible.

**Comment by postapczuk** [comment]
@snug Yep

**Comment by jancborchardt** [comment]
@snug @postapczuk yeah, this would also improve the first run experience. There should probably not be any entries with "Long-press to pick favorite" to start with, but just

- the probable default apps set, maybe just 3
- a temporary hint that you can long-press to change
- the "+ Add favorite" below the list
- an entry at the top of the "Pick an app" list to set it to "None" which removes the row (in case you only want to have 1 favorite app)
