### ISSUE TITLE
No background for status bar

### ISSUE THREAD

**Issue by jancborchardt** [postapczuk/Light-Android-Launcher#20]
Currently the status bar has a black background and the text is hidden by it when scrolling. It would be nice if it would be transparent like in gallery apps, or even have no background at all.

Found some resources on how to do this:
- https://stackoverflow.com/questions/29311078/android-completely-transparent-status-bar
- https://stackoverflow.com/questions/42313382/translucent-status-bar-in-android

**Comment by postapczuk** [comment]
done

**Comment by jancborchardt** [comment]
@postapczuk this looks really good by the way! Makes a big difference :)
