### ISSUE TITLE
"+ Add favorite app" text should be less distracting

### ISSUE THREAD

**Issue by jancborchardt** [postapczuk/Light-Android-Launcher#27]
Currently the "+ Add favorite app" text is very present in the favorites view. 2 ways we can improve that:
- [x] Make the text half-opacity or half-grey
- [ ] Only show the full text on first run. As soon as you chose your first favorite app, the label could be just the "+"

**Comment by snug** [comment]
Definitely don't want "+ add favorite app" on the screen at all times, but I'm not sure if we need + either. What about an edit mode (activated by long pressing down anywhere on the screen) that allows you to add apps that way?

It might be a good idea if we created a design document and edited some screenshots to figure out what might be the best fit. I could get to work on this in the next couple of days if you guys wanted? I've opened an issue for it, but let me know if it's something you guys would be keen on.

**Comment by jancborchardt** [comment]
Yeah, using this for a bit, the extra row with only the "+" even is distracting. Once you set your favorites, you don’t change them all the time.


> What about an edit mode (activated by long pressing down anywhere on the screen) that allows you to add apps that way?

Seems ok, but remember that most people don’t actually know about long-press, so we will have to have a hint about that once at the start. Probably best to do several proposals about how it could work if you like. :)

**Comment by postapczuk** [comment]
applied dimming. the "+" was ugly.
