### ISSUE TITLE
Low profile mode not working on main favorites screen

### ISSUE THREAD

**Issue by jancborchardt** [postapczuk/Light-Android-Launcher#43]
The low profile mode initially works everywhere, but then it seems to stop working on the main/favorites page where the status bar is shown permanently. Switching to the all apps section sets to low profile, but going back to the main screen (by gesture or back button) goes out of low profile again.

Can you reproduce this @postapczuk @snug?

**Comment by jancborchardt** [comment]
The clock is still there in low profile mode though.

It's not a big issue, just inconsistent between the screens, and when I added the low profile mode, the intention was to have it low profile on both views.

**Comment by postapczuk** [comment]
It's not abut the clock, it's about important notifications that doesn't appear in bar if it is low profile

**Comment by jancborchardt** [comment]
Any event reminder or messages notification usually have an importance set though? When I set a medication reminder in the Calendar (Etar) there's 2 ways it can prominently remind:
- Popup in the middle of the screen
- Notification shows on the top of the screen, a bit less intrusive but very present

**Comment by jancborchardt** [comment]
It's not so important. Will close the issue. :)
